### ISSUE TITLE
node support

### ISSUE THREAD

**Issue by benmanu** [brettt89/silverstripe-web#14]
I'm exploring the best approach to add node support (for npm/yarn dependencies) to the docker image. The use case being to use this as the base image for CircleCI testing SilverStripe sites (with docker out of the box in v2), extending to run our Karma test suite.

Options:
1. Add it directly to this image. The issue with this being node versions are fickle so having a fixed dep tied to this repo doesn't seem to be the best approach...
2. Extend the image. This is mentioned in issue #10, this would be a quick approach but could we have a master list of flavours in this repo to avoid duplicate builds? and possibly a "how to" guide for extending?
3. Something different...

**Comment by brettt89** [comment]
Hi @benmanu 

Thank you for your feedback. I think you are on the right track regarding "extending" the image. I am unsure how CircleCI currently uses Docker for testing, is there a guide available that you are using?

I am also unsure what you mean by "master list of flavours"? haha.
If you are after a list of installed services on this image, you should be able to find everything that is installed / configured in the Dockerfile of this repo
https://github.com/brettt89/silverstripe-web/blob/master/platform/Dockerfile

In regards to extending a docker image. All that is required is a Dockerfile (E.g. like the one in the link above) that has the FROM set to brettt89/silverstripe-web
E.g. https://docs.docker.com/engine/reference/builder/#from

Using this image in the FROM will allow you to run additional commands (E.g. installing npm) on top of everything currently installed on this image.

**Comment by benmanu** [comment]
Hey @brettt89,

I've got a CircleCI guide documented here (quite new so still ironing out kinks):
https://github.com/benmanu/silverstripe-circleci-docs
https://github.com/benmanu/silverstripe-circleci-docs/blob/master/.circleci/config.yml

With the "master list of flavours" (definitely keep this name haha) I'm thinking if it's extended in different ways, how to share out the different extensions? That way there isn't double ups of docker builds floating around doing the same thing.
eg:
```
## Master list of flavours
- Node v6.11: https://hub.docker.com/r/bmanu/silverstripe-web-node/
- Node v5.4: {other link}
- Some other extension: {other link}
```

Using the FROM to extend this build works a treat 👍

**Comment by brettt89** [comment]
@benmanu What if we opened up the brettt89/silverstripe-web docker image so that you can also push additional tags to the image?

E.g. Then we could have things like "brettt89/silverstripe-web:1.0-node-v6.11" similar to how PHP does all there different versions with Apache and fpm etc (https://hub.docker.com/_/php/).

Would this be something you would be interested in participating with? I can add you as a contributor to both repo and docker hub.

**Comment by benmanu** [comment]
@brettt89 I would be quite keen to jump onboard, sounds like a plan!
