### ISSUE TITLE
Limited GD functionality?

### ISSUE THREAD

**Issue by leepowelldev** [brettt89/silverstripe-web#19]
Can't seem up resize images on the backend to the _resampled directory. I'm using the 5.6 tag with a SS v3 project.  I've debugged back to there being no available backend provided from GD for the resizing. None of the following seem to be available 'imagecreatefromgif', 'imagecreatefromjpeg', 'imagecreatefrompng'. Attached is the output from phpinfo.

<img width="959" alt="screen shot 2017-11-20 at 10 07 47" src="https://user-images.githubusercontent.com/602052/33013204-1f62a9ba-cddb-11e7-984a-414e87109138.png">

**Comment by leepowelldev** [comment]
Fixed by running:
docker-php-ext-configure gd --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ --with-zlib-dir=/usr/include/

Did you want me to create a PR to add?

**Comment by blueo** [comment]
I've added the jpeg + freetype options here: https://github.com/brettt89/silverstripe-web/pull/23

**Comment by brettt89** [comment]
Fixed: #23
