### ISSUE TITLE
Add Imagick extension

### ISSUE THREAD

**Issue by blueo** [brettt89/silverstripe-web#21]
To reflect the platform environment could we install imagick?

**Comment by fspringveldt** [comment]
Do you mind raising a PR for that @blueo?

**Comment by blueo** [comment]
sure @fspringveldt  added here: https://github.com/brettt89/silverstripe-web/pull/22
I didn't add them to the alpine files - hope that's ok, the dockerfiles didn't appear to reference an alpine image so wasn't sure if they were all go?

**Comment by fspringveldt** [comment]
@brettt89 mind having a look at the above PR when you get a chance?

**Comment by fspringveldt** [comment]
Closed via #22
