### ISSUE TITLE
Confusing use of 'alpine'

### ISSUE THREAD

**Issue by stojg** [brettt89/silverstripe-web#24]
I had a look around and thought that the 'alpine' version was derived from the alpine linux container, which it doesn't seem to be. Could it be renamed to something that wouldn't cause namespace issues?

**Comment by brettt89** [comment]
Agreed, I need to go back and build an actual "alpine" build.

**Comment by brettt89** [comment]
Alpine builds are being removed in the next release (though tag will still persist in a deprecated state until actual alpine builds are completed.
