### ISSUE TITLE
setting document root to /public

### ISSUE THREAD

**Issue by gaambo** [brettt89/silverstripe-web#27]
hi there, 
i'm just trying to setup my first silverstripe environment with this docker-image, docker-compose and composer. normally i'd set the document root to the /public folder but the documentroot is set in the dockerfile in this image and not changeable (except forking this repository). also the `create-project silverstripe` command does not seem to do it this way - instead a `.htaccess` in the root directory rewrites all requests to the `/public` folder - is this a good idea and if yes, why? 

i think a better aproach would be to allow customization of the document root via an environment variable as in the official apache docker images.

**Comment by brettt89** [comment]
Hi Gaambo,

I will put this as a requested feature to be able to configure the Document Root using environment variables.

In the meantime, you could create your own Dockerfile FROM this build, and modify the Apache config settings for web root to be `/public`.
