### ISSUE TITLE
config file is not copied into /sites-enabled folder

### ISSUE THREAD

**Issue by fwanghe** [brettt89/silverstripe-web#30]
Hey,

Just read the Dockerfile and found that the hardcoded apache config file in the Dockerfile is written into the config file in `etc/apache2//sites-available` instead of copying it into the `/etc/apache2/sites-enabled/ `folder in the container. Does it mean Docker will pick the config file from the `/sites-available` folder?

Cheers
Frank

**Comment by jmlagace** [comment]
Hello Frank,

It does not need to. 

If you take a look at /etc/apache2/sites-enabled/ you'll see a symlink pointing to the /etc/apache2/sites-available/

![image](https://user-images.githubusercontent.com/143464/57661040-3169e800-75b7-11e9-9845-a163fb73993d.png)

**Comment by fwanghe** [comment]
Got it, thanks Jean!
