### ISSUE TITLE
PHP 7.2 / PHP 7.3 upgrade

### ISSUE THREAD

**Issue by ssmarco** [brettt89/silverstripe-web#32]
Hi Brett,
Do you have PHP 7.2/7.3 upgrade in the pipeline?

**Comment by wilr** [comment]
ping @brettt89 if no upgrade is in the pipeline is there an alternative image which mirrors SSP PHP 7.3?

**Comment by brettt89** [comment]
Hi team,

Apologies for the lack of updates on this environment. I will see if I can find some time over the next week to push out some updates on this for later PHP versions.

**Comment by brettt89** [comment]
Upgrade is on its way (going through final set of testing, just fixing up some bugs with PHP 7.2 / 7.3 and extensions on docker. Hoping to have a release later today.

**Comment by brettt89** [comment]
This has now been released. Check out the new `README.md` file in https://hub.docker.com/r/brettt89/silverstripe-web

**Comment by wilr** [comment]
Thanks @brettt89 👍
