### ISSUE TITLE
About cron

### ISSUE THREAD

**Issue by rouralberto** [brettt89/silverstripe-web#33]
Hi, I'm trying to use this base image for my Silverstripe application (`brettt89/silverstripe-web`) and I want to know if there is a built-in solution to support cronjobs.

I checked the documentation at https://docs.silverstripe.org/en/3/developer_guides/cli/#running-regular-tasks-with-cron

**Comment by jmlagace** [comment]
Hello Alberto,

Doing cronjobs in a Docker is normally achieved outside of the container.

On a single host, you would set up the cronjob on the host. And (using the documentation from the Silverstripe website as the base for the example)

```
* * * * * docker run --rm -w /your/site/folder **PARAMETERS FOR THAT SPECIFIC ENVIRONMENT** **APPIMAGE** /your/site/folder/sake dev/tasks/MyTask
```

That will spin a one-off container that will call sake with the URL.  Make sure to replace  **PARAMETERS FOR THAT SPECIFIC ENVIRONMENT** **APPIMAGE** with the right settings to mount the proper volume, be on the right network, anything you would be using for the application itself (outsing exposing ports).

If you are running with Swarm, you would define an additional service in your stack, one whose role is to to the sake call to dev/tasks/MyTask. How it's done will be dependant on what you utilize to create your cluster (be it docker-compose, swarmpit or creating services yourself). 

For the scheduling part, I would then use  `rayyanqcri/swarm-scheduler` (https://github.com/rayyanqcri/swarm-scheduler) to schedule the work on the cluster. Assuming you are using a service I would use this pattern as the command

docker service scale **NAMEOFSERVICE**=0 && **NAMEOFSERVICE**=1

where **NAMEOFSERVICE** is the name of the service on your cluster (you get those through `docker service ls`).

I hope this helps. 

Regards,
