### ISSUE TITLE
How to install imagemagick?

### ISSUE THREAD

**Issue by spekulatius** [brettt89/silverstripe-web#49]
Hey @brettt89 

I'm trying to install imagemagick (php-imagick) but I can't find any package manager in the container (apk, apt-get, yum, snap). How would I install it?

Cheers,
Peter

**Comment by michalkleiner** [comment]
`RUN install-php-extensions imagick` doesn't work?

**Comment by spekulatius** [comment]
I've tried `RUN docker-php-ext-install imagick` and it didn't work

**Comment by michalkleiner** [comment]
Can you try what I suggested? That's how all other modules are installed.

**Comment by spekulatius** [comment]
Sure, I took it for a similar way. Give me a few minutes to see @michalkleiner

**Comment by spekulatius** [comment]
Cool, that seemed to have worked @michalkleiner. What's the difference between `RUN docker-php-ext-install imagick` and `RUN install-php-extensions imagick`?

**Comment by spekulatius** [comment]
Resolved thanks to @michalkleiner!
