### ISSUE TITLE
Is additional image tag dockerhub push required?

### ISSUE THREAD

**Issue by josephlewisnz** [brettt89/silverstripe-web#52]
Hey there,

My image is currently being built from
`FROM brettt89/silverstripe-web:7.3-apache`

Went to install xdebug on my image and recieved:
```
 > [15/18] RUN docker-php-extension-installer xdebug:
#19 0.691 /bin/bash: docker-php-extension-installer: command not found
```

Looking at the repo, it looks like the php extensions script should be included.
`COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/install-php-extensions`

However, looking at the docker hub it looks like there are many image:tags that have not been pushed to recently? Which I assume would include this line?

Not 100% sure what the flow should look like here, so please close if this is not an issue.

**Comment by michalkleiner** [comment]
Seems your RUN command is not running the correct command, it should be `RUN install-php-extensions ...`, not `docker-php-extension-installer` as in your CLI output excerpt.

**Comment by josephlewisnz** [comment]
Thanks @michalkleiner 

Looks to run fine now. 

Not sure if we would want to update the README or the images to match?

**Comment by michalkleiner** [comment]
Created a PR to update the README.
https://github.com/brettt89/silverstripe-docker/pull/53
