### ISSUE TITLE
Unable to run new images due to "Config variable ${ENVVAR} is not defined"

### ISSUE THREAD

**Issue by nicole-ashley** [brettt89/silverstripe-web#55]
Since this morning, when I try to build new images they log this error on startup and then refuse all requests:
```sh
AH00111: Config variable ${ENVVAR} is not defined
AH01630: client denied by server configuration: /srv/
- - [06/Sep/2021:22:34:04 +0000] "GET / HTTP/1.1" 403 400 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
AH01630: client denied by server configuration: /srv/favicon.ico
- - [06/Sep/2021:22:34:04 +0000] "GET /favicon.ico HTTP/1.1" 403 400 "/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
```

Nothing has changed in my configuration at all. `DOCUMENT_ROOT` is set to `/srv/public`.

Based on the commit history, I can't quite figure out what has broken things. I can see that you removed `ENVVAR` in https://github.com/brettt89/silverstripe-docker/pull/45, but then reintroduced it in https://github.com/brettt89/silverstripe-docker/pull/51 when you moved the build files around. However that was back in December; unless you didn't publish to Docker hub between then and last night?

**Comment by nicole-ashley** [comment]
@brettt89 Any thoughts on this? I've been unable to deploy new builds since the last release.

**Comment by brettt89** [comment]
Hi @nikrolls , yes this does look to be a bug that snuck back in. I am currently pushing up a PR to fix this. However you should be able to temporarily resolve this by setting `ENVVAR` to the same value as `DOCUMENT_ROOT` . I will get a fix pushed up, tested and released for this shortly. Apologies for the inconvenience.

**Comment by nicole-ashley** [comment]
Thanks @brettt89! That workaround seems obvious now you say it. I'll give it a go and thanks for looking into the fix.

**Comment by brettt89** [comment]
Am just pushing up fixes now to Docker hub.

**Comment by brettt89** [comment]
New images have been pushed up to Docker Hub. execute a `docker pull` on images to pull down latest fixes.

**Comment by nicole-ashley** [comment]
Thanks so much, @brettt89!
