### ISSUE TITLE
Yarn, yawn!

### ISSUE THREAD

**Issue by digitall-it** [brettt89/silverstripe-web#57]
For the sake of me, I couldn't get yarn to work! What did I do wrong?
I did that, install my web container:
```
apt-get install npm
npm install -g yarn
```
when I do yarn install, it complains that there's no "install" directory.

**Comment by ndorfin** [comment]
I'm a novice at such environments but the following might help…

Make sure your `package.json` file has been copied over to the docker container:

```Dockerfile
COPY ["package.json", "/var/www/html"]
```

**Comment by davejtoews** [comment]
FWIW it's likely not necessary to run yarn on the same image as Silverstripe. We run our projects on 3 separate images. This repo for apache/php, the official mysql image for database, and the official node image for front-end builds.

**Comment by brettt89** [comment]
As mentioned by @davejtoews, yarn / node is not included in these images. They are PHP/Apache images for running an already built Silverstripe website.
