### ISSUE TITLE
Feature request: Imagick support

### ISSUE THREAD

**Issue by davejtoews** [brettt89/silverstripe-web#67]
Browsing old issues it seems it was once included, but is not anymore. Was it deliberately removed?

I can get it working for myself as simple as:

Dockerfile
```
FROM brettt89/silverstripe-web:7.4-apache

RUN install-php-extensions imagick
```

But it would be nice to have it working out of the box.

**Comment by brettt89** [comment]
Imagick was removed from image as it was not used by all use-cases. These images are designed to be light-weight with only the minimum required configuration and modules required to run Silverstripe, however can be extended for individual application use-cases.

As you have already described, you can add your own customisations to these images by extension in Dockerfile's for each of your projects to install and configure additional modules or customisations.
