### ISSUE TITLE
Feature Request: Xdebug

### ISSUE THREAD

**Issue by davejtoews** [brettt89/silverstripe-web#68]
I've been able to set up XDebug in a project with the following dockerfile.

```
FROM brettt89/silverstripe-web:8.1-apache
RUN install-php-extensions xdebug

# Add Xdebug to PHP configuration
RUN echo "" >> /etc/php.ini \
    && echo "[xdebug]" >> /etc/php.ini \
    && echo "zend_extension = xdebug" >> /etc/php.ini \
    && echo "xdebug.start_with_request = 1" >> /etc/php.ini \
    && echo "xdebug.remote_port = 9003" >> /etc/php.ini \
    && echo "xdebug.client_port = 9003" >> /etc/php.ini
```

The php.ini stuff might need to be project specific and could be handled by mounting a local php.ini w/ docker-compose.yml, so it could be excluded, but it would be nice to have the PHP extension installed out of the box

**Comment by catharsisjelly** [comment]
Yes to this, I just came to see if there was already an issue for adding XDEBUG. I'll give this setup a go and report back.

**Comment by brettt89** [comment]
This image is intended to be a broad-use image that can be used for all purposes. As such it does not include development specific configurations.

Adding of additional modules and configuration can be achieved through extending of these images as you appear to already be doing.

This ensures the images are flexible for all use-cases and not just for development.
