### ISSUE TITLE
Sendmail

### ISSUE THREAD

**Issue by digitall-it** [brettt89/silverstripe-web#8]
Tried to send mail to a mailhog/mailcatcher container but without avail. Is sendmail installed?

**Comment by brettt89** [comment]
Hi @digitall-it ,

Thank you for your question. sendmail is not installed by default on this image, however you can use the same process in Issue #10 to extend brettt89/silverstripe-web and install you mail service as desired (e.g. sendmail / mailhog / ssmtp, etc)
